platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run electron:buildWinPublish

test: off

branches:
  only:
    - master